version: '2'
#volumes:
#  octoprint: {}
services:
  octoprint:
    build: ./
    restart: always
    #volumes:
    #  - octoprint:/octoprint
    privileged: true
    ports:
      - '80:5000'
  config-editor:
    image: linuxserver/code-server
    ports:
      - 8443:8443
    depends_on:
      - octoprint
    restart: unless-stopped
    environment:
      - PUID=0
      - GUID=0
      - TZ=America/NewYork
    #volumes:
    #  - octoprint:/octoprint
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: always
    environment:
      - 'SCRAPE_PORT=9100'
    ports:
      - 9100:9100
  mdns-publisher:
    build: ./mdns-publisher
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
  restreamer:
    image: datarhei/restreamer-aarch64:latest
    container_name: restreamer
    restart: always
    ports:
      - 8080:8080