version: '2'
volumes:
  octoprint-logs: {}
services:
  octoprint:
    build: ./
    restart: always
    volumes:
      - octoprint-logs:/octoprint/octoprint/logs
    privileged: true
    ports:
      - '80:5000'
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'   
  # config-editor:
  #   image: linuxserver/code-server
  #   ports:
  #     - 8443:8443
  #   depends_on:
  #     - octoprint
  #   restart: unless-stopped
  #   environment:
  #     - PUID=0
  #     - GUID=0
  #     - TZ=America/NewYork
  #   #volumes:
  #   #  - octoprint:/octoprint
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    privileged: true
    restart: always
    environment:
      - 'SCRAPE_PORT=9100'
    ports:
      - 9100:9100
  mdns-publisher:
    build: ./mdns-publisher
    restart: always
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
  restreamer:
    image: datarhei/restreamer-aarch64:latest
    restart: always
    ports:
      - 8080:8080
  promtail:
    build: ./promtail
    restart: always
    depends_on:
      - octoprint
    volumes:
      - octoprint-logs:/octoprint-logs
    command: -config.file=/etc/promtail/promtail.yml -log.level=debug -config.expand-env=true
    labels:
      io.balena.features.journal-logs: '1'
  octodash:
    restart: always
    build: ./octodash
    privileged: true
    environment:
      - UDEV=1
    depends_on:
      - octoprint