accessControl:
  salt: HeiITgEYC1Zz9eAvghWAZEJTl1UQgFAw
  userfile: /octoprint/octoprint/users.yaml
api:
  allowCrossOrigin: true
  key: 62BFEB0AC6C44DABB2AA7A6E1148474A
plugins:
  PrintJobHistory:
    capturePrintJobHistoryMode: always
    pluginCheckActivated: false
    selectedFilamentTrackerPlugin: no plugin installed/enabled
    showPrintJobDialogAfterPrint: false
    takePluginThumbnailAfterPrint: false
  snapstream:
    fallbackonly: false
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1615917600
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1611568800
      _plugins:
        read_until: 1620795600
      _releases:
        read_until: 1620652800
    enabled_channels:
      - _important
      - _releases
  discovery:
    upnpUuid: cb75080a-2627-4375-8d1d-e98f8b46b694
  errortracking:
    unique_id: f6ff05df-c12e-46c4-a180-e82fc67e7489
  gcodeviewer:
    _config_version: 1
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: true
    unique_id: ea1e1779-820f-4dc9-a02d-37e982ba2228
  virtual_printer:
    _config_version: 1
printerProfiles:
  default: _default
server:
  commands:
    serverRestartCommand: s6-svc -r /var/run/s6/services/octoprint
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: fZRUcxXFwut5GNg6oiAAq67mLdjCGDkw
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
webcam:
  ffmpeg: /usr/bin/ffmpeg
  snapshot: http://localhost:8080/?action=snapshot
  stream: /webcam/?action=stream
