FROM --platform=linux/arm64 octoprint/octoprint:minimal

ENV PYTHONUSERBASE /octoprint/plugins
ENV PIP_USER true
ENV PATH "${PYTHONUSERBASE}/bin:${PATH}"
RUN pip install --no-cache-dir \
    "https://github.com/marian42/octoprint-preheat/archive/master.zip" 

# Seed the initial config.yaml
COPY ./config.yaml /data/config.yaml


CMD ["octoprint","serve","--iknowwhatimdoing","--host","0.0.0.0"]
