#!/bin/bash
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

if $WIFI_AUTOCONFIGURE; then
    # Is there an active WiFi connection?
    iwgetid -r  

    if [ $? -eq 0 ]; then
        printf 'Skipping WiFi Connect\n'
    else
        printf 'Starting WiFi Connect\n'
        /opt/wifi-connect/wifi-connect --portal-listening-port 80 --portal-gateway 10.52.32.1 --portal-dhcp-range 10.52.32.2,10.52.32.200 --portal-ssid OctoPrint-$OCTOPRINT_HOSTNAME --ui-directory /opt/wifi-connect/ui
    fi
fi 

exec octoprint serve --iknowwhatimdoing --host 0.0.0.0 --port 80 --basedir /octoprint/octoprint 