name: Deploy to Balena Cloud
on:
  push:
    branches:
      - master
      - develop
      
jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: g_josh_wright/balena-octoprint
          create_tag: true
          layer_cache: true
          default_branch: master
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"