#!/usr/bin/with-contenv bash

: "${ENABLE_MJPG_STREAMER:=false}"

# disable mjpg-streamer service if not enabled
if ! $ENABLE_MJPG_STREAMER; then
  rm -rf /etc/services.d/mjpg-streamer
fi

exec octoprint --basedir /octoprint/octoprint config set --json webcam "{\"ffmpeg\":\"/usr/bin/ffmpeg\",\"snapshot\":\"http://10.1.2.101:8080/images/live.jpg\",\"stream\":\"http://10.1.2.101:8080/hls/live.stream.m3u8\"}"