#!/usr/bin/with-contenv bash

curl -X PATCH --header "Content-Type:application/json" \
    --data "{\"network\": {\"hostname\": \"$OCTOPRINT_HOSTNAME\"}}" \
    "$BALENA_SUPERVISOR_ADDRESS/v1/device/host-config?apikey=$BALENA_SUPERVISOR_API_KEY"

