#!/usr/bin/with-contenv bash

curl -X PATCH --header "Content-Type:application/json" \
    --data "{\"network\": {\"hostname\": \"balena_$OCTOPRINT_HOSTNAME\"}}" \
    "$BALENA_SUPERVISOR_ADDRESS/v1/device/host-config?apikey=$BALENA_SUPERVISOR_API_KEY"

HOSTIP=$(curl -s GET -H "Authorization: Bearer $BALENA_SUPERVISOR_API_KEY"   -H "Content-Type: application/json"    "$BALENA_SUPERVISOR_ADDRESS/v1/device" | jq -r .ip_address | cut -d' ' -f 1)
