#!/usr/bin/with-contenv bash
#Add notification token and change device name based on Env Var
#TODO: Do these tokens need to be re-generated per machine?  It seems to work w/o doing that, should probably ask developer
#octoprint --basedir /octoprint/octoprint config set --json plugins.octopod.tokens "{\"apnsToken\": \"$OCTOPOD_APNS\",\"date\": \"05\/28\/21 02:45:39\",\"deviceName\": \"iPhone\",\"languageCode\": \"en\",\"printerID\": \"$OCTOPOD_PRINTERID\",\"printerName\": \"$OCTOPRINT_HOSTNAME\"}"